name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar aplicación
        run: node app.js

      - name: Ejecutar pruebas
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparar sitio
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v4
